[package]
name = "rustcalc"
version = "0.1.0"
authors = ["Patrik Svensson <patrik@patriksvensson.se>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.53"
failure = "0.1.6"

[lib]
crate-type =["cdylib"]